!function $TrustValueRatio($ratio)
  !return "<font:Consolas><b><back:white><color:black> " + $ratio + " </color></back></b></font>"
!endfunction

!function $AggregatedRisk($risk)
  !return "<font:Consolas><b><back:#darkorchid><color:#white> " + $risk + " </color></back></b></font>"
!endfunction

!function $AggregatedRisks($risks)
  !$risk_string = ""
  !$index = 0
  !$length = %strlen($risks)
  !$current_risk = ""
  !while $index < $length
    !$char = %substr($risks, $index, 1)
    !if (%strpos($char, ":") == 0)
      !$risk_string = $risk_string + $AggregatedRisk($current_risk) + " "
      !$current_risk = ""
    !else
      !$current_risk = $current_risk + $char
    !endif
    !$index = $index + 1
  !endwhile
  !return $risk_string + $AggregatedRisk($current_risk)
!endfunction

!function $Stride($stride_code)
  !$stride_string = ""
  !if (%strpos($stride_code, "S")>=0)
    !$stride_string = $stride_string + "<color:#blue><back:#lightblue> S </back></color>"
  !endif
  !if (%strpos($stride_code, "T")>=0)
    !$stride_string = $stride_string + "<color:#green><back:#lightgreen> T </back></color>"
  !endif
  !if (%strpos($stride_code, "R")>=0)
    !$stride_string = $stride_string + "<color:#brown><back:#orange> R </back></color>"
  !endif
  !if (%strpos($stride_code, "I")>=0)
    !$stride_string = $stride_string + "<color:#darkgoldenrod><back:#yellow> I </back></color>"
  !endif
  !if (%strpos($stride_code, "D")>=0)
    !$stride_string = $stride_string + "<color:#firebrick><back:#pink> D </back></color>"
  !endif
  !if (%strpos($stride_code, "E")>=0)
    !$stride_string = $stride_string + "<color:#purple><back:#plum> E </back></color>"
  !endif
  !return "<font:Consolas><b>" + $stride_string + "</b></font>"
!endfunction

skinparam card {
  backgroundColor<<risk_table>> White
  BorderColor<<risk_table>> Black
  shadowing<<risk_table>> false  
}

!procedure $RiskTable()
hide stereotype
card risks <<risk_table>>
!endprocedure

!procedure $AddRisk($risk_id, $text)
| <back:#darkorchid><font:consolas><color:#white><b> $risk_id </b></color></font></back> | $text |
!endprocedure
