@startuml Example using STRIDE
!include https://raw.githubusercontent.com/paulbrimicombe/stride-plantuml/main/stride.puml

Bob -> Alice: $TrustValueRatio("5:2") $Stride("STRIDE") $AggregatedRisks("R1:R2") "Hello"

$RiskTable() [
  === Aggregated Risks
  ----
  $AggregatedRisk("R1") Details of aggregated risk number 1.
  This could be a very long description or a very short one!
  ----
  $AggregatedRisk("R2") Details of aggregated risk number 2
]
@enduml
